@hostname = 127.0.0.1
@port = 8000
@host = {{hostname}}:{{port}}

###

GET http://{{host}}/face

###

GET http://{{host}}/schema

###

GET http://{{host}}/openapi.json

###

GET http://{{host}}/context

###

GET http://{{host}}/context/hours

###

GET http://{{host}}/context/location

###

GET http://{{host}}/context/query

###

GET http://{{host}}/products-today

###

PUT http://{{host}}/context/hours/7

###

PUT http://{{host}}/context/hours
content-type: application/json

{
    "value": 11
}

###

PUT http://{{host}}/context
content-type: application/json

{
    "hid": "hours",
    "value": 12
}

###
